name: Build Raspberry Pi Image

on:
  workflow_dispatch:
    # Add inputs here if you need to pass device name/HMAC later
    # inputs:
    #   device_name:
    #     description: 'Device Name for the image'
    #     required: true
    #     default: 'raspberry-pi-01'
    #   device_hmac:
    #     description: 'Device HMAC for provisioning'
    #     required: true
    #     default: 'DEFAULT_HMAC_VALUE'

jobs:
  build:
    runs-on: self-hosted # Runs on a standard GitHub Linux server

    steps:
      - name: Checkout Repository
        # Downloads your code (Dockerfile, scripts, services)
        uses: actions/checkout@v4

      - name: Set up QEMU for Docker
        # Installs emulation tools needed for building ARM images on x86 servers
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        # Sets up Docker's advanced builder tool
        uses: docker/setup-buildx-action@v3

      - name: Build the image assembler
        # Runs your Dockerfile to prepare the OS and tools
        run: docker build -t pi-image-assembler --platform=linux/arm64 .

      - name: Create final .img file
        # Runs the assembler container with privileges to create the disk image
        run: |
          docker run --privileged --name temp-assembler pi-image-assembler

      - name: Extract the .img file
        # Copies the finished pi-image.img out of the container
        run: |
          docker cp temp-assembler:/output/pi-image.img ./pi-image.img
          docker rm temp-assembler # Cleans up the temporary container
          
      - name: Upload Image Artifact
        # Uploads the final pi-image.img so you can download it
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-image # Name of the downloadable file
          path: ./pi-image.img     # Path to the file to upload